<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.7.0 on win32)" generated="20190116 11:03:33.055" rpa="false">
<suite id="s1" name="Test" source="C:\Users\ldgomes\Desktop\Projetos\Robot_Framework_Study\Roche_Test_Appium\tests\test.robot">
<test id="s1-t1" name="Test Case 01">
<kw name="Abrir Aplicacao" library="resource" type="setup">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>${SERVER}</arg>
<arg>platformName=Android</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APK}</arg>
</arguments>
<status status="PASS" starttime="20190116 11:03:33.317" endtime="20190116 11:03:40.664"></status>
</kw>
<status status="PASS" starttime="20190116 11:03:33.316" endtime="20190116 11:03:40.664"></status>
</kw>
<kw name="Checar imagem logotipo" library="resource">
<kw name="Wait Until Element Is Visible" library="AppiumLibrary">
<doc>Waits until element specified with `locator` is visible.</doc>
<arguments>
<arg>id=robot2</arg>
</arguments>
<msg timestamp="20190116 11:13:58.744" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/ef56f11a-d7b9-4c67-b604-0ff46caef1c4/source</msg>
<status status="FAIL" starttime="20190116 11:03:40.665" endtime="20190116 11:14:51.714"></status>
</kw>
<status status="FAIL" starttime="20190116 11:03:40.664" endtime="20190116 11:14:51.714"></status>
</kw>
<kw name="Fechar Aplicacao" library="resource" type="teardown">
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<status status="PASS" starttime="20190116 11:14:51.715" endtime="20190116 11:14:53.060"></status>
</kw>
<status status="PASS" starttime="20190116 11:14:51.715" endtime="20190116 11:14:53.060"></status>
</kw>
<status status="FAIL" starttime="20190116 11:03:33.316" endtime="20190116 11:14:53.062" critical="yes">Execution terminated by signal</status>
</test>
<status status="FAIL" starttime="20190116 11:03:33.057" endtime="20190116 11:14:53.065"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190116 11:13:58.744" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/ef56f11a-d7b9-4c67-b604-0ff46caef1c4/source</msg>
</errors>
</robot>
