<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.7.0 on win32)" generated="20190116 13:44:31.160" rpa="false">
<suite id="s1" name="Test" source="C:\Users\ldgomes\Desktop\Projetos\Robot_Framework_Study\Roche_Test_Appium\tests\test.robot">
<test id="s1-t1" name="Test Case 01">
<kw name="Abrir Aplicacao" library="resource" type="setup">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>${SERVER}</arg>
<arg>platformName=Android</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APK}</arg>
</arguments>
<msg timestamp="20190116 13:44:45.302" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\ldgomes\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s H7AZB602F881PR5 install C\:/Users/ldgomes/Desktop/Projetos/Robot_Framework_Study/Roche_Test_Appium/APK/roche.apk' exited with code 1'; Stderr: 'adb: failed to install C:/Users/ldgomes/Desktop/Projetos/Robot_Framework_Study/Roche_Test_Appium/APK/roche.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/br.com.roche.casosclinicos-dPAydFUdPxTrYsSCwdrwOw==: Can't install because provider name com.roche.stf.DocumentViewerPlugin.fileprovider (in package br.com.roche.casosclinicos) is already used by com.roche.stf]'; Code: '1'
</msg>
<status status="FAIL" starttime="20190116 13:44:34.000" endtime="20190116 13:44:45.302"></status>
</kw>
<status status="FAIL" starttime="20190116 13:44:33.999" endtime="20190116 13:44:45.303"></status>
</kw>
<kw name="Fechar Aplicacao" library="resource" type="teardown">
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<msg timestamp="20190116 13:44:45.305" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20190116 13:44:45.304" endtime="20190116 13:44:45.305"></status>
</kw>
<status status="FAIL" starttime="20190116 13:44:45.303" endtime="20190116 13:44:45.306">No application is open</status>
</kw>
<status status="FAIL" starttime="20190116 13:44:33.998" endtime="20190116 13:44:45.306" critical="yes">Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\ldgomes\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s H7AZB602F881PR5 install C\:/Users/ldgomes/Desktop/Projetos/Robot_Framework_Study/Roche_Test_Appium/APK/roche.apk' exited with code 1'; Stderr: 'adb: failed to install C:/Users/ldgomes/Desktop/Projetos/Robot_Framework_Study/Roche_Test_Appium/APK/roche.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/br.com.roche.casosclinicos-dPAydFUdPxTrYsSCwdrwOw==: Can't install because provider name com.roche.stf.DocumentViewerPlugin.fileprovider (in package br.com.roche.casosclinicos) is already used by com.roche.stf]'; Code: '1'


Also teardown failed:
No application is open</status>
</test>
<status status="FAIL" starttime="20190116 13:44:31.163" endtime="20190116 13:44:45.330"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
